#!/bin/bash
if [ -z "$repo" ]; then
    repo=$PWD
fi
#TODO: change path to your path
cd go-oapi-codegen
mvn package
cd $repo
cp go-oapi-codegen/target/go-oapi-codegen-openapi-generator-0.1.14.jar  go-oapi-codegen.jar
generatorUrl=$(cat $repo/bindgen-config.json | json generate.generatorUrl)
wget "${generatorUrl}" -O $repo/openapi-generator-cli.jar