name: Test Bindings

on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:
  
jobs:
  test:
    uses: onshape-public/openapi-utilities/.github/workflows/test-bindings.yml@bugfix/update-version-in-workflow
    secrets:
      BOT_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
      ONSHAPE_API_ACCESS_KEY: ${{ secrets.ONSHAPE_API_KEY_DEMO_C }}
      ONSHAPE_API_SECRET_KEY: ${{ secrets.ONSHAPE_API_SECRET_DEMO_C }}