name: Update Bindings

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch:
    uses: onshape-public/openapi-utilities/.github/workflows/update-bindings.yml@bugfix/update-version-in-workflow
    secrets:
      BOT_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
      ONSHAPE_API_ACCESS_KEY: ${{ secrets.ONSHAPE_API_KEY_DEMO_C }}
      ONSHAPE_API_SECRET_KEY: ${{ secrets.ONSHAPE_API_SECRET_DEMO_C }}